# Generated by Django 4.2.7 on 2023-11-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChordSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=50, verbose_name="Song Title")),
                ("initial_key", models.PositiveSmallIntegerField(null=True)),
                ("initial_tempo", models.PositiveSmallIntegerField(null=True)),
                ("initial_metre_1", models.PositiveSmallIntegerField(default=4)),
                ("initial_metre_2", models.PositiveSmallIntegerField(default=4)),
                ("content", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="ChordSheetRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.PositiveSmallIntegerField()),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Music.chordsheet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
