# Generated by Django 4.2.7 on 2023-11-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Shows", "0005_alter_event_title"),
        ("Music", "0002_chordsheetroles_lastupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventItemOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nr", models.PositiveSmallIntegerField()),
                ("proposed_duration", models.DurationField(null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Shows.event",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Music.chordsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["event", "nr"],
                "unique_together": {("event", "nr")},
            },
        ),
    ]
