# Generated by Django 4.2.7 on 2023-11-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Shows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="EventRoles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
