# Generated by Django 4.2.7 on 2023-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shows", "0004_alter_event_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.TextField(max_length=100),
        ),
    ]
